services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: autoprd
      POSTGRES_PASSWORD: autoprd
      POSTGRES_DB: autoprd
    ports:
      - "5432:5432"
    volumes:
      - autoprd_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - autoprd_redis:/data

volumes:
  autoprd_pg:
  autoprd_redis:
